# Generated by Django 6.1 on 2026-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_salary',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='min_salary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
