# Generated by Django 4.2.11 on 2026-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_post_max_salary_post_min_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
        migrations.AddField(
            model_name='post',
            name='contact_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_salary',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
