# Generated by Django 4.2.11 on 2026-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_post_applied_remove_post_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
