# Generated by Django 4.2.11 on 2026-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_post_company_location_post_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
